<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GlobalHotKey" Version="1.1.0" />
        <PackageReference Include="WindowsBase" Version="4.6.1055.0" />
            <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
    </ItemGroup>

</Project>